In [1]:
# 시리즈 원소에 함수 매핑
# Series객체.apply(매핑함수)

import seaborn as sns
import pandas as pd

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'fare']]
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [2]:
def add_10(n):
    return n + 10

def add_two_obj(a, b):
    return a + b

print(add_10(10))
print(add_two_obj(10, 10))

20
20

In [3]:
df['age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [4]:
sr1 = df['age'].apply(add_10)
sr1.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [5]:
imsi = lambda n: n + 10
imsi(10)

20

In [6]:
sr2 = df['age'].apply(lambda n: n + 10)
sr2.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [7]:
sr3 = df['age'].apply(add_two_obj, b=10)
sr3.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [8]:
sr4 = df['age'].apply(lambda a, b: a + b, b=10)
sr4.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [9]:
# 데이터프레임의 각 결에 함수 매핑 p.358
df

def calculate_state(col):
    max_val = col.max()
    min_val = col.min()
    mean_val = col.mean()
    median_val = col.median()

    return pd.Series(
        [max_val, min_val, mean_val, median_val],
        index=['Max', 'Min', 'Mean', 'Median']
    )

result_df = df.apply(calculate_state, axis=0)
result_df

              age        fare
Max     80.000000  512.329200
Min      0.420000    0.000000
Mean    29.699118   32.204208
Median  28.000000   14.454200

In [10]:
result_sr = df.apply(lambda x: x.max() - x.min())
result_sr

age      79.5800
fare    512.3292
dtype: float64

In [11]:
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [12]:
def calculate_diff_avg(row):
    diff = row.max() - row.min()
    avg = row.mean()

    return pd.Series([diff, avg], index=['차이', '평균'])

result_df2 = df.apply(calculate_diff_avg, axis=1)
result_df2

          차이        평균
0    14.7500  14.62500
1    33.2833  54.64165
2    18.0750  16.96250
3    18.1000  44.05000
4    26.9500  21.52500
..       ...       ...
886  14.0000  20.00000
887  11.0000  24.50000
888   0.0000  23.45000
889   4.0000  28.00000
890  24.2500  19.87500

[891 rows x 2 columns]

In [13]:
titanic = sns.load_dataset('titanic')
df1 = titanic.loc[:, ['age', 'fare']]
df2 = titanic.loc[:, ['embark_town', 'embarked']]

def missing_value(df):
    return df.isnull()

result_df = df1.pipe(missing_value)
result_df

       age   fare
0    False  False
1    False  False
2    False  False
3    False  False
4    False  False
..     ...    ...
886  False  False
887  False  False
888   True  False
889  False  False
890  False  False

[891 rows x 2 columns]

In [14]:
def missing_count(df):
    return missing_value(df).sum()

df1.pipe(missing_count)

# df1.isnull().sum()

age     177
fare      0
dtype: int64

In [15]:
df2.head()

   embark_town embarked
0  Southampton        S
1    Cherbourg        C
2  Southampton        S
3  Southampton        S
4  Southampton        S

In [16]:
def extract_initial(df):
    df['town_initial'] = df['embark_town'].str[0]
    return df

def verify_initial(df):
    df['verified'] = df['embarked'] == df['town_initial']
    return df

imsi = extract_initial(df2)
verify_initial(imsi)

     embark_town embarked town_initial  verified
0    Southampton        S            S      True
1      Cherbourg        C            C      True
2    Southampton        S            S      True
3    Southampton        S            S      True
4    Southampton        S            S      True
..           ...      ...          ...       ...
886  Southampton        S            S      True
887  Southampton        S            S      True
888  Southampton        S            S      True
889    Cherbourg        C            C      True
890   Queenstown        Q            Q      True

[891 rows x 4 columns]

In [17]:
df2.pipe(extract_initial).pipe(verify_initial)

     embark_town embarked town_initial  verified
0    Southampton        S            S      True
1      Cherbourg        C            C      True
2    Southampton        S            S      True
3    Southampton        S            S      True
4    Southampton        S            S      True
..           ...      ...          ...       ...
886  Southampton        S            S      True
887  Southampton        S            S      True
888  Southampton        S            S      True
889    Cherbourg        C            C      True
890   Queenstown        Q            Q      True

[891 rows x 4 columns]