In [1]:
import pandas as pd

In [2]:
# 시리즈 = pandas.Series(데이터)
# 데이터프레임 = pandas.DataFrame(데이터)

In [7]:
dict_data = {
    'c0': [1, 2, 3],
    'c1': [4, 5, 6],
    'c2': [7, 8, 9],
    'c3': [10, 11, 12],
    'c4': [13, 14, 15],
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [19]:
# 행 인덱스 / 열 이름 설정
import pandas as pd

data = [
    [15, '남', '덕영중'],
    [17, '여', '수리중']
]

df = pd.DataFrame(data, index=['준서', '예은'], columns=['나이', '성별', '학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [20]:
print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [21]:
df.index = ['학생1', '학생2']

print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [22]:
df.columns = ['연령', '남녀', '소속']

print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [23]:
import pandas as pd

data = [
    [15, '남', '덕영중'],
    [17, '여', '수리중']
]

df = pd.DataFrame(data, index=['준서', '예은'], columns=['나이', '성별', '학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [26]:
df.rename(columns={'나이': '연령', '성별': '남녀', '학교': '소속'})

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [29]:
print(df)
# rename만으로는 update가 안 되었음을 확인.

# 그래서 재할당
df = df.rename(columns={'나이': '연령', '성별': '남녀', '학교': '소속'})
print(df)

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중
    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [40]:
df = df.rename(index={'준서': '학생1', '예은': '학생2'})
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [66]:
# 행/열 삭제
# 행 삭제: DataFrame객체.drop(행 인덱스 또는 배열, axis=0 또는 axis='index')    => 여기서 기본은 axis=0으로 가로 방향. 나중에 다른 거 나옴
# 열 삭제: DataFrame객체.drop(열 이름 또는 배열, axis=1 또는 axis='columns')

import pandas as pd

exam_data = {
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90],
}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
print(df)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [54]:
df2 = df.copy()

# 재할당 필요
df2 = df2.drop('우현')
print(df2)

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [58]:
df3 = df.copy()

df3 = df3.drop(['우현', '인아'], axis=0)
print(df3)

    수학  영어  음악   체육
서준  90  98  85  100

In [61]:
df4 = df.copy()

df4 = df4.drop(['우현', '인아'], axis='index')
print(df4)

    수학  영어  음악   체육
서준  90  98  85  100

In [63]:
df5 = df.copy()

df5.drop(index=['우현'])

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [69]:
# 열 삭제
df2 = df.copy()
df2 = df2.drop('수학', axis=1)
print(df2)

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [73]:
df3 = df.copy()
df3 = df3.drop(['영어', '음악'], axis=1)
print(df3)

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [77]:
df4 = df.copy()
df4 = df4.drop(['영어', '체육'], axis='columns')
print(df4)

    수학   음악
서준  90   85
우현  80   95
인아  70  100

In [82]:
df5 = df.copy()
df5 = df5.drop(columns=['수학'])
print(df5)

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [ ]:
# 행 선택
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [99]:
print(df.loc['서준'])
print(type(df.loc['서준']))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [103]:
label1 = df.loc['서준']
position1 = df.iloc[0]

In [108]:
print(label1, end='\n\n')
print(position1)

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [126]:
print(df.loc[['서준', '우현']], end='\n\n')
print(df.iloc[[0, 1]], end='\n\n')

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [124]:
type(df.loc[['서준', '우현']])

pandas.DataFrame

In [125]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [127]:
# 행 선택
print(df.loc['서준':'우현'], end='\n\n')
print(df.iloc[0:1])

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100

In [130]:
# 열 선택
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [135]:
type(df['수학'])

pandas.Series

In [139]:
print(df.영어)
type(df.영어)

서준    98
우현    89
인아    95
Name: 영어, dtype: int64

pandas.Series

In [142]:
print(df[['영어', '체육']])
type(df[['영어', '체육']])

    영어   체육
서준  98  100
우현  89   90
인아  95   90

pandas.DataFrame

In [149]:
print(type(df['영어']))
print(df['영어'], end='\n\n')

print(type(df[['영어']]))
print(df[['영어']])

<class 'pandas.Series'>
서준    98
우현    89
인아    95
Name: 영어, dtype: int64

<class 'pandas.DataFrame'>
    영어
서준  98
우현  89
인아  95

In [164]:
# 원소 선택

exam_data = {
    '이름': ['서준', '우현', '인아'],
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90],
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [165]:
print(df.loc[0:2], end='\n\n')
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [166]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [169]:
df1 = df.set_index('이름')
df1

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [172]:
print(df1.loc['서준'], end='\n\n')
print(df1.iloc[0])

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [174]:
df1

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [186]:
print(df1.loc['서준']['음악'])
print(df1.loc['서준', '음악'])
print(df1.iloc[0, 2])

85
85
85

In [194]:
print(df1.loc['서준', ['음악', '체육']])
print()
print(df1.iloc[0, [2, 3]])

음악     85
체육    100
Name: 서준, dtype: int64

음악     85
체육    100
Name: 서준, dtype: int64

In [202]:
print(df1.loc['서준', '음악':'체육'])
print()
print(df1.iloc[0, 2:])

음악     85
체육    100
Name: 서준, dtype: int64

음악     85
체육    100
Name: 서준, dtype: int64