In [1]:
import pandas as pd

df = pd.read_csv('./data/stock-data.csv')

print(df.head(), end='\n\n')
print(df.info(), end='\n\n')
print(df.isnull().sum())   # 결측치가 있는지 확인 => 전부 0: 없다

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB
None

Date      0
Close     0
Start     0
High      0
Low       0
Volume    0
dtype: int64

In [2]:
# 문자열을 Timestamp로 변환

df['new_date'] = pd.to_datetime(df['Date'])
print(df.head())
print(df.info())

         Date  Close  Start   High    Low  Volume   new_date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB
None

In [3]:
df = df.set_index('new_date')
df.drop('Date', axis=1, inplace=True)
df.head()

            Close  Start   High    Low  Volume
new_date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [4]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 20 entries, 2018-07-02 to 2018-06-01
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   20 non-null     int64
 1   Start   20 non-null     int64
 2   High    20 non-null     int64
 3   Low     20 non-null     int64
 4   Volume  20 non-null     int64
dtypes: int64(5)
memory usage: 960.0 bytes

In [5]:
pd.DatetimeIndex([
    '2022-12-15', '2023/01/25', '2022.12.25'
])

DatetimeIndex(['2022-12-15', '2023-01-25', '2022-12-25'], dtype='datetime64[us]', freq=None)

In [6]:
pd.DatetimeIndex([
    '2022:12:15'    # 날짜 형태가 아니라서 오류 발생
])

DateParseError: hour must be in 0..23, not 2022: 2022:12:15

In [7]:
pd.Timestamp('2023-12-25')

Timestamp('2023-12-25 00:00:00')

In [8]:
pd.Timestamp('2023:12:25')  # 날짜 형태가 아니라서 오류 발생

DateParseError: hour must be in 0..23, not 2023: 2023:12:25

In [9]:
pd.to_datetime('2025/12/25')

Timestamp('2025-12-25 00:00:00')

In [10]:
pd.to_datetime('2025:12:25', format='%Y:%m:%d')

Timestamp('2025-12-25 00:00:00')

In [11]:
pd.to_datetime('2025년 12월 25일', format='%Y년 %m월 %d일')

Timestamp('2025-12-25 00:00:00')

In [12]:
# pd.to_datetime('05-12-2023 23:59:59')
pd.to_datetime('05-12-2023 23:59:59', format='%d-%m-%Y %H:%M:%S')

Timestamp('2023-12-05 23:59:59')

In [13]:
# timestamp를 이용해서 period로 변환

dates = ['2019-01-01', '2020-03-01', '2021-06-01', '2021-09-09']

ts_dates = pd.to_datetime(dates)
ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01', '2021-09-09'], dtype='datetime64[us]', freq=None)

In [14]:
pr_day = ts_dates.to_period(freq='D')
pr_day

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01', '2021-09-09'], dtype='period[D]')

In [15]:
pr_month = ts_dates.to_period(freq='M')
pr_month

PeriodIndex(['2019-01', '2020-03', '2021-06', '2021-09'], dtype='period[M]')

In [16]:
pr_year = ts_dates.to_period(freq="Y")
pr_year

PeriodIndex(['2019', '2020', '2021', '2021'], dtype='period[Y-DEC]')

In [17]:
# 시계열 데이터 만들기
ts_ms = pd.date_range(
    start='2024-01-01',
    end=None,
    periods=6,
    freq="MS",
    tz='Asia/Seoul',
)

ts_ms

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [18]:
ts_me = pd.date_range(
    start='2024-01-01',
    periods=6,
    freq="ME",
    tz='Asia/Seoul',
)

ts_me

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [19]:
ts_3m = pd.date_range(
    '2024-01-01',
    periods=6,
    freq='3MS',
    tz='Asia/Seoul'
)

ts_3m

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [20]:
# 시계열 데이터 활용
df = pd.read_csv('./data/stock-data.csv')
df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [21]:
df['new_Date'] = pd.to_datetime(df['Date'])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [22]:
df['year'] = df['new_Date'].dt.year
df['month'] = df['new_Date'].dt.month
df['day'] = df['new_Date'].dt.day

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
 7   year      20 non-null     int32
 8   month     20 non-null     int32
 9   day       20 non-null     int32
dtypes: datetime64[us](1), int32(3), int64(5), str(1)
memory usage: 1.5 KB

In [23]:
df['Date_yr'] = df['new_Date'].dt.to_period(freq='Y')
df['Date_m'] = df['new_Date'].dt.to_period(freq='M')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
 7   year      20 non-null     int32
 8   month     20 non-null     int32
 9   day       20 non-null     int32
 10  Date_yr   20 non-null     period[Y-DEC]
 11  Date_m    20 non-null     period[M]
dtypes: datetime64[us](1), int32(3), int64(5), period[M](1), period[Y-DEC](1), str(1)
memory usage: 1.8 KB

In [24]:
# 2018년 6월 데이터만 추출 (문자열 속성 활용)
df_june = df[df['Date_m'].astype(str).str.fullmatch('2018-06')]
df_june.head()

,Date,Close,Start,High,Low,Volume,new_Date,year,month,day,Date_yr,Date_m
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,6,29,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,6,28,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,6,27,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,6,26,2018,2018-06
5,2018-06-25,11150,11400,11450,11000,55519,2018-06-25,2018,6,25,2018,2018-06

In [25]:
# 2018년 6월 데이터만 추출 (Period 객체 활용)
df_june2 = df[df['Date_m'] == pd.Period('2018-06')]
df_june2.head()

,Date,Close,Start,High,Low,Volume,new_Date,year,month,day,Date_yr,Date_m
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,6,29,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,6,28,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,6,27,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,6,26,2018,2018-06
5,2018-06-25,11150,11400,11450,11000,55519,2018-06-25,2018,6,25,2018,2018-06

In [26]:
# 원하는 열을 새로운 행 인덱스로 지정
df_june = df_june.set_index('new_Date')
df_june.head()

,Date,Close,Start,High,Low,Volume,year,month,day,Date_yr,Date_m
new_Date,,,,,,,,,,,
2018-06-29,2018-06-29,10700,10550,10900,9990,170253,2018,6,29,2018,2018-06
2018-06-28,2018-06-28,10400,10900,10950,10150,155769,2018,6,28,2018,2018-06
2018-06-27,2018-06-27,10900,10800,11050,10500,133548,2018,6,27,2018,2018-06
2018-06-26,2018-06-26,10800,10900,11000,10700,63039,2018,6,26,2018,2018-06
2018-06-25,2018-06-25,11150,11400,11450,11000,55519,2018,6,25,2018,2018-06

In [27]:
# 시간인덱스 활용
df = pd.read_csv('./data/stock-data.csv')
df['new_Date'] = pd.to_datetime(df['Date'])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [28]:
df = df.set_index('new_Date')
df

                  Date  Close  Start   High    Low  Volume
new_Date
2018-07-02  2018-07-02  10100  10850  10900  10000  137977
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-26  2018-06-26  10800  10900  11000  10700   63039
2018-06-25  2018-06-25  11150  11400  11450  11000   55519
2018-06-22  2018-06-22  11300  11250  11450  10750  134805
2018-06-21  2018-06-21  11200  11350  11750  11200  133002
2018-06-20  2018-06-20  11550  11200  11600  10900  308596
2018-06-19  2018-06-19  11300  11850  11950  11300  180656
2018-06-18  2018-06-18  12000  13400  13400  12000  309787
2018-06-15  2018-06-15  13400  13600  13600  12900  201376
2018-06-14  2018-06-14  13450  13200  13700  13150  347451
2018-06-12  2018-06-12  13200  12200  13300  12050  558148
2018-06-11  2018-06-11  11950  12000  12250  11950   62293
2018-06-08  2018-06-08  11950  11950  12200  11800   59258
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-01  2018-06-01  11900  11800  12100  11750   32062

In [31]:
df = df.sort_index()    # sort_values()
df

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258
2018-06-11  2018-06-11  11950  12000  12250  11950   62293
2018-06-12  2018-06-12  13200  12200  13300  12050  558148
2018-06-14  2018-06-14  13450  13200  13700  13150  347451
2018-06-15  2018-06-15  13400  13600  13600  12900  201376
2018-06-18  2018-06-18  12000  13400  13400  12000  309787
2018-06-19  2018-06-19  11300  11850  11950  11300  180656
2018-06-20  2018-06-20  11550  11200  11600  10900  308596
2018-06-21  2018-06-21  11200  11350  11750  11200  133002
2018-06-22  2018-06-22  11300  11250  11450  10750  134805
2018-06-25  2018-06-25  11150  11400  11450  11000   55519
2018-06-26  2018-06-26  10800  10900  11000  10700   63039
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [32]:
df.loc['2018-06-27']

Date      2018-06-27
Close          10900
Start          10800
High           11050
Low            10500
Volume        133548
Name: 2018-06-27 00:00:00, dtype: object

In [34]:
df.loc['2018-06-27':'2018-07-02']

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [40]:
cond = df.index < '2018-06-05'
print(cond)

df[cond]

[ True  True False False False False False False False False False False
 False False False False False False False False]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171

In [41]:
pd.Timestamp('2018-06-27')

Timestamp('2018-06-27 00:00:00')

In [42]:
pd.Timestamp(2018, 6, 27)

Timestamp('2018-06-27 00:00:00')

In [44]:
df.loc[pd.Timestamp(2018, 6, 27) : pd.Timestamp(2018, 6, 29)]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253

In [48]:
df.loc[
    pd.Timestamp(2018, 6, 27, 10, 30, 15) : pd.Timestamp(2018, 7, 2, 23, 53, 59)
]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977