In [2]:
# 시리즈 연산
# 시리즈객체 + 연산자(+, -, *, /) + 숫자(스칼라)

dict_data = {
    '국어': 100,
    '영어': 80,
    '수학': 90
}

import pandas as pd

student1 = pd.Series(dict_data)
print(student1)

국어    100
영어     80
수학     90
dtype: int64

In [5]:
percentage = student1 / 100
percentage

국어    1.0
영어    0.8
수학    0.9
dtype: float64

In [7]:
# 시리즈 vs 시리즈
student2 = pd.Series({'수학': 80, '국어': 90, '영어': 80})

print(student1)
print()
print(student2)

국어    100
영어     80
수학     90
dtype: int64

수학    80
국어    90
영어    80
dtype: int64

In [8]:
addition = student1 + student2
addition

국어    190
수학    170
영어    160
dtype: int64

In [10]:
subtraction = student1 - student2
subtraction

국어    10
수학    10
영어     0
dtype: int64

In [11]:
multiplication = student1 * student2
multiplication

국어    9000
수학    7200
영어    6400
dtype: int64

In [15]:
division = student1 / student2
division

국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [16]:
pd.DataFrame([addition, subtraction, multiplication, division], index=['덧셈', '뺄셈', '곱셈', '나눗셈'])

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [19]:
# NaN 값이 있는 시리즈 연산
import pandas as pd
import numpy as np

student1 = pd.Series({
    '국어': np.nan,
    '영어': 80,
    '수학': 90
})

student2 = pd.Series({
    '수학': 80,
    '국어': 90,
})

print(student1)
print()
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

In [20]:
addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2

print(addition)
print()
print(subtraction)
print()
print(multiplication)
print()
print(division)

국어      NaN
수학    170.0
영어      NaN
dtype: float64

국어     NaN
수학    10.0
영어     NaN
dtype: float64

국어       NaN
수학    7200.0
영어       NaN
dtype: float64

국어      NaN
수학    1.125
영어      NaN
dtype: float64

In [ ]:
result = pd.DataFrame([addition, subtraction, multiplication, division], index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
result

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [32]:
# 연산 메서드
student1 = pd.Series({
    '국어': np.nan,
    '영어': 80,
    '수학': 90
})

student2 = pd.Series({
    '수학': 80,
    '국어': 90,
})

print(student1)
print()
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

In [41]:
sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

result = pd.DataFrame([sr_add, sr_sub, sr_mul, sr_div], index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
result

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [44]:
# 데이터프레임의 연산
# 데이터프레임 vs. 숫자(스칼라)

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [48]:
print(titanic.shape)
print(titanic.ndim)
print(type(titanic))

(891, 15)
2
<class 'pandas.DataFrame'>

In [53]:
df = titanic.loc[:, ['age', 'fare']]
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [55]:
addition = df + 10
addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [57]:
# 데이터프레임 vs. 데이터프레임
df
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [61]:
titanic = sns.load_dataset('titanic')
titanic.loc[:, ['age', 'fare']]
titanic.head()
titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [64]:
addition = df + 10
addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [67]:
subtraction = addition - df
subtraction.head()

    age  fare
0  10.0  10.0
1  10.0  10.0
2  10.0  10.0
3  10.0  10.0
4  10.0  10.0

In [74]:
addition.tail()
subtraction.tail()

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0

In [75]:
sample1 = addition.tail()
sample1

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [78]:
sample2 = subtraction.tail().fillna(0.0)
sample2

      age  fare
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [92]:
df_add = sample1.add(sample2, fill_value=0)
df_sub = sample1.sub(sample2, fill_value=0)
df_mul = sample1.mul(sample2, fill_value=0)
df_div = sample1.div(sample2, fill_value=0)
# df_div = sample1.div(sample2).fillna(0)

print(df_add, end='\n\n')
print(df_sub, end='\n\n')
print(df_mul, end='\n\n')
print(df_div, end='\n\n')

      age   fare
886  47.0  33.00
887  39.0  50.00
888   0.0  43.45
889  46.0  50.00
890  52.0  27.75

      age   fare
886  27.0  13.00
887  19.0  30.00
888   0.0  23.45
889  26.0  30.00
890  32.0   7.75

       age   fare
886  370.0  230.0
887  290.0  400.0
888    0.0  334.5
889  360.0  400.0
890  420.0  177.5

     age   fare
886  3.7  2.300
887  2.9  4.000
888  NaN  3.345
889  3.6  4.000
890  4.2  1.775